CREATE TABLE users (
	id UUID PRIMARY KEY NOT NULL,
	username VARCHAR(20) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	credits BIGINT DEFAULT 0 NOT NULL,
	role INT DEFAULT 1 NOT NULL,
	status INT DEFAULT 1 NOT NULL,
	country VARCHAR(5) DEFAULT 'US' NOT NULL,
	rating INT DEFAULT 0 NOT NULL,
	avatar VARCHAR(255) DEFAULT 'default.png',
	creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bans (
	id SERIAL PRIMARY KEY,
	userbanned VARCHAR(20) NOT NULL,
	username VARCHAR(20) NOT NULL,
	reason TEXT,
	bantime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
